### ISSUE TITLE
no semitechnologies/transformers-inference:baai-bge-m3-onnx in dockerhub

### ISSUE THREAD

**Issue by ltm920716** [weaviate/t2v-transformers-models#84]
hi,
 there is no image in dokerhub called 'semitechnologies/transformers-inference:baai-bge-m3-onnx'

  and from https://weaviate.io/developers/weaviate/installation/docker-compose, the yaml is:
```
---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.3
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:baai-bge-m3
    environment:
      ENABLE_CUDA: '0'
```

there is no cr.weaviate.io/semitechnologies/transformers-inference:baai-bge-m3 neither
